/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorAutoridad;
import ec.edu.ups.controlador.ControladorContrayente;
import ec.edu.ups.controlador.ControladorMatrimonio;
import ec.edu.ups.controlador.ControladorContrayente;
import ec.edu.ups.modelo.Matrimonio;
import java.time.LocalDate;

/**
 *
 * @author ariel
 */
public class Principal extends javax.swing.JFrame {
    
    private VentanaRegistrarUsuario ventanaAgregarNuevoJuez;
    private VentanaIniciarSecion ventanaIniciarSecion;
    private VentanaRegistros ventanaRegistros;
    private VentanaMatrimoniosRegistrados ventanaMatrimoniosRegistrados;
    private ControladorAutoridad controladorAutoridad;
    private ControladorContrayente controladorContrayente;
    private ControladorMatrimonio controladorMatrimonio;
    

    /**
     * Creates new form VentanaPrincipal
     */
    public Principal() {
        initComponents();
        controladorAutoridad = ControladorAutoridad.getInstancia();
        controladorContrayente = controladorContrayente.getInstancia();
        controladorMatrimonio = ControladorMatrimonio.getInstancia();
        ventanaAgregarNuevoJuez = new VentanaRegistrarUsuario(controladorAutoridad);
        ventanaIniciarSecion = new VentanaIniciarSecion(controladorAutoridad, controladorContrayente, controladorMatrimonio);
        ventanaRegistros = new VentanaRegistros(controladorAutoridad, controladorContrayente);
        ventanaMatrimoniosRegistrados = new VentanaMatrimoniosRegistrados(controladorMatrimonio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelIcono = new javax.swing.JLabel();
        jButtonIniciarSecion = new javax.swing.JButton();
        jButtonPersonasRegistradas = new javax.swing.JButton();
        jButtonAgregarNuevoJuez = new javax.swing.JButton();
        jButtonMatrimoniosRegistrados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Matrimonios UPS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabelTitulo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("MATRIMONIOS   UPS");

        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/recien-casados.png"))); // NOI18N

        jButtonIniciarSecion.setBackground(new java.awt.Color(204, 204, 204));
        jButtonIniciarSecion.setText("Registrar Matrimonio");
        jButtonIniciarSecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarSecionActionPerformed(evt);
            }
        });

        jButtonPersonasRegistradas.setBackground(new java.awt.Color(204, 204, 204));
        jButtonPersonasRegistradas.setText("Registros de Personas");
        jButtonPersonasRegistradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersonasRegistradasActionPerformed(evt);
            }
        });

        jButtonAgregarNuevoJuez.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAgregarNuevoJuez.setText("Registar Autoridad");
        jButtonAgregarNuevoJuez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarNuevoJuezActionPerformed(evt);
            }
        });

        jButtonMatrimoniosRegistrados.setBackground(new java.awt.Color(204, 204, 204));
        jButtonMatrimoniosRegistrados.setText("Listas de Matrimonios");
        jButtonMatrimoniosRegistrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMatrimoniosRegistradosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(101, 101, 101))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonIniciarSecion, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelIcono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAgregarNuevoJuez, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonPersonasRegistradas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonMatrimoniosRegistrados, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelIcono))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonIniciarSecion)
                            .addComponent(jButtonAgregarNuevoJuez))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPersonasRegistradas)
                    .addComponent(jButtonMatrimoniosRegistrados))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarSecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarSecionActionPerformed
        // TODO add your handling code here:
        ventanaIniciarSecion.setVisible(true);
    }//GEN-LAST:event_jButtonIniciarSecionActionPerformed

    private void jButtonPersonasRegistradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersonasRegistradasActionPerformed
        // TODO add your handling code here:
        ventanaRegistros.setVisible(true);
        ventanaRegistros.cargarDatosPersonas();
    }//GEN-LAST:event_jButtonPersonasRegistradasActionPerformed

    private void jButtonAgregarNuevoJuezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarNuevoJuezActionPerformed
        // TODO add your handling code here:
        ventanaAgregarNuevoJuez.setVisible(true);
    }//GEN-LAST:event_jButtonAgregarNuevoJuezActionPerformed

    private void jButtonMatrimoniosRegistradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMatrimoniosRegistradosActionPerformed
        // TODO add your handling code here:
        ventanaMatrimoniosRegistrados.setVisible(true);
        ventanaMatrimoniosRegistrados.cargarDatos();
    }//GEN-LAST:event_jButtonMatrimoniosRegistradosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarNuevoJuez;
    private javax.swing.JButton jButtonIniciarSecion;
    private javax.swing.JButton jButtonMatrimoniosRegistrados;
    private javax.swing.JButton jButtonPersonasRegistradas;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
