/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ConexionIMatrimonio;
import ec.edu.ups.controlador.ControladorContrayente;
import ec.edu.ups.controlador.ControladorTestigo;
import ec.edu.ups.controlador.iMatrimonio;
import ec.edu.ups.modelo.Contrayente;

/**
 *
 * @author Andres
 */
public class RegistarMatrimonio extends javax.swing.JInternalFrame {
private Novio novio;
private Novia novia;
private VTestigo vTestigo;
private ControladorTestigo controladorTestigo;
private  ControladorContrayente controladorContrayente;
    /**
     * Creates new form RegistarMatrimonio
     */
    public RegistarMatrimonio(ControladorContrayente controladorContrayente) {
        initComponents();
        novio=new Novio(controladorContrayente);
        novia=new Novia(controladorContrayente);
        vTestigo=new VTestigo(controladorTestigo);
        jDesktopPane1.add(novia);
        jDesktopPane1.add(novio);
        jDesktopPane1.add(vTestigo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnNovio = new javax.swing.JButton();
        btnNovia = new javax.swing.JButton();
        btnTestigo = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jButton1.setText("Casar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnNovio.setText("Novio");
        btnNovio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovioActionPerformed(evt);
            }
        });

        btnNovia.setText("Novia");
        btnNovia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoviaActionPerformed(evt);
            }
        });

        btnTestigo.setText("Testigos");
        btnTestigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnNovio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(btnNovia)
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTestigo)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovio)
                    .addComponent(btnNovia))
                .addGap(44, 44, 44)
                .addComponent(btnTestigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(53, 53, 53))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovioActionPerformed
        novio.setVisible(true);
    }//GEN-LAST:event_btnNovioActionPerformed

    private void btnNoviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoviaActionPerformed
        novia.setVisible(true);
    }//GEN-LAST:event_btnNoviaActionPerformed

    private void btnTestigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestigoActionPerformed
        vTestigo.setVisible(true);
    }//GEN-LAST:event_btnTestigoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
ConexionIMatrimonio c = new ConexionIMatrimonio();  
 iMatrimonio c1= c.getConexion("Contrayente"); 
 Contrayente ac=new Contrayente(novio.getTxtCedula().getText(),novio.getTxtDireccion().getText(),novio.getTxtFecha().getText(),novio.getTxtGenero().getText(),novio.getTxtNombre().getText(),novio.getTxtApellido().getText());
 controladorContrayente.agregarPareja(ac);   
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovia;
    private javax.swing.JButton btnNovio;
    private javax.swing.JButton btnTestigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
