/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorAutoridad;
import ec.edu.ups.controlador.ControladorContrayente;
import ec.edu.ups.modelo.Autoridad;
import ec.edu.ups.modelo.Contrayente;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ariel
 */
public class VentanaRegistros extends javax.swing.JFrame {

    /**
     * Creates new form VentanaJueces
     */
    
    ControladorAutoridad controladorAutoridad;
    ControladorContrayente controladorContrayente;
    
    public VentanaRegistros(ControladorAutoridad controladorAutoridad, ControladorContrayente controladorContrayente) {
        initComponents();
        this.controladorAutoridad = controladorAutoridad;
        this.controladorContrayente = controladorContrayente;
        
    }
    
    public void cargarDatosPersonas() {
        DefaultTableModel modelo = (DefaultTableModel) jTableJueces.getModel();
        modelo.setRowCount(0);
        
        for (Contrayente p : controladorContrayente.getListado()) {
            Object[] rowData = {p.getNombre(), p.getApellido(), p.getCedula(), p.getDireccion(), p.getGenero(), p.getEstadoCivil()};
            modelo.addRow(rowData);
        }
        jTableJueces.setModel(modelo);
    }
    
    public void cargarDatosJueces() {
        DefaultTableModel modelo = (DefaultTableModel) jTableJueces.getModel();
        modelo.setRowCount(0);
        
        for (Autoridad juez : controladorAutoridad.getListado()) {
            Object[] rowData = {juez.getNombre(), juez.getApellido(), juez.getCedula(), juez.getDireccion(), juez.getGenero(), juez.getEstadoCivil()};
            modelo.addRow(rowData);
        }
        jTableJueces.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableJueces = new javax.swing.JTable();
        jButtonJueces = new javax.swing.JButton();
        jButtonPersonaRegistradas = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabelTitulo.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Registros");

        jTableJueces.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Cedula", "Direccion", "Genero", "Estado civil"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableJueces);

        jButtonJueces.setText("Jueces");
        jButtonJueces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJuecesActionPerformed(evt);
            }
        });

        jButtonPersonaRegistradas.setText("Contrayentes");
        jButtonPersonaRegistradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersonaRegistradasActionPerformed(evt);
            }
        });

        jButton1.setText("Matrimonios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabelTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonJueces)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonPersonaRegistradas, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButtonJueces)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonPersonaRegistradas)
                        .addGap(29, 29, 29)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJuecesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJuecesActionPerformed
        // TODO add your handling code here:
        cargarDatosJueces();
    }//GEN-LAST:event_jButtonJuecesActionPerformed

    private void jButtonPersonaRegistradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersonaRegistradasActionPerformed
        // TODO add your handling code here:
        cargarDatosPersonas();
    }//GEN-LAST:event_jButtonPersonaRegistradasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonJueces;
    private javax.swing.JButton jButtonPersonaRegistradas;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableJueces;
    // End of variables declaration//GEN-END:variables
}
